src/ezinvmvc.Web.Mvc/Controllers/SalesOrdersController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading.Tasks;
using Abp.Application.Services.Dto;
using AutoMapper;
using ezinvmvc.App.Vendors;
using ezinvmvc.App.Vendors.Dto;
using ezinvmvc.Controllers;
using ezinvmvc.Web.Models.Vendors;
using Microsoft.AspNetCore.Mvc;

namespace ezinvmvc.Web.Mvc.Controllers
{
    public class SalesOrdersController : ezinvmvcControllerBase
    {
        public IActionResult Index()
        {
            return View();
        }
        public async Task<ActionResult> Create()
        {
            return View();
        }
        public async Task<ActionResult> Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
    }
}

src/ezinvmvc.Web.Mvc/Views/SalesOrders/Index.cshtml
@using Abp.Application.Services.Dto
@using ezinvmvc.Web.Startup
@using ezinvmvc.Authorization

@{
    ViewBag.CurrentPageName = PageNames.Sales_Orders;
}
@section scripts
    {
    <script src="~/view-resources/Views/SalesOrders/Index.js" asp-append-version="true"></script>
}

<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-md-6 col-xl-6">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Sales Orders</h1>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="float-right" style="padding-top:10px">
                    @if (IsGranted(PermissionNames.Pages_Sales_Orders_Export))
                    {
                        <button id="ExportProductToExcelButton" class="btn btn-outline-success btn-sm"><i class="fa fa-file-excel-o"></i>&nbsp;Export</button>
                    }
                    @if (IsGranted(PermissionNames.Pages_Sales_Orders_Create))
                    {
                        <button id="CreateNewButton" onclick="window.open('@Url.Action("Create", "SalesOrders")')" class="btn btn-outline-primary btn-sm"><i class="fa fa-plus"></i>&nbsp; Create New</button>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="animated fadeIn">
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        @* Filter *@
                        <div class="row align-items-center m--margin-bottom-10">
                            <div class="col-md-3 col-xl-3">
                                <div class="form-group">
                                    <input type="text" id="DateFrom" name="DateFrom" class="input-md form-control-md form-control date-picker" required>
                                </div>
                            </div>
                            <div class="col-md-3 col-xl-3">
                                <div class="form-group">
                                    <input type="text" id="DateTo" name="DateTo" class="input-md form-control-md form-control date-picker" required>
                                </div>
                            </div>
                            <div class="col-md-3 col-xl-3">
                                <div class="form-group">
                                    <select id="StatusTypes" class="selectpicker form-control input-md form-control-md" multiple data-live-search="true">
                                        <option value="1">Draft</option>
                                        <option value="2">For Delivery</option>
                                        <option value="3">Completed</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-3 col-xl-3">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" id="SearchFilter" class="form-control-md m-input" placeholder="Search..." value="">
                                        <span class="input-group-btn">
                                            <button id="SearchButton" class="btn btn-default" type="submit"><i class="fa fa-search" aria-label="@L("Search")"></i></button>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        @* List *@
                        <div class="row align-items-center">
                            <div class="col-xl-12">
                                <table id="SalesOrdersTable" class="display table table-striped table-bordered table-hover dt-responsive nowrap">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th width="15%">Id</th>@*Id*@
                                            <th width="45%">Client</th>
                                            <th width="15%">Date</th>@*Date*@
                                            <th width="15%">Delivery</th>@*Date*@
                                            <th width="10%">Status</th>
                                            <th width="15%">Total</th>
                                            <th width="4%">@L("Actions")</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>